############################################################
# Project.
############################################################
project:
  type: website
  resources:
    - Assets/PDFs/resume.pdf

############################################################
# Language.
############################################################
language:
  search-text-placeholder: Search

############################################################
# Website.
############################################################
website:
  favicon: Assets/Images/logo-icon.png
  title: ""
  page-navigation: true ## Provides next and previous page links in footer.
  back-to-top-navigation: true
  reader-mode: false ## Enables/disables the icon that hides sidebar and toc contents.
  bread-crumbs: false
  search:
    location: navbar
    type: textbox ## Selects the type of search UI.
    copy-button: true
    show-item-context: true ## Shows search result parents.

  navbar:
    logo: Assets/Images/logo-icon.png
    pinned: true ## Keeps the navbar visible during page scrolling.
    left:
      - text: Home
        href: index.qmd
      
      - text: "Courses"
        menu:
          - text: C# Programming
            href: Courses/CSharp/index.qmd

          - text: ASP.NET Core Development
            href: Courses/ASPNET/index.qmd

          - text: Forex Trading
            href: Courses/Forex/index.qmd                         

      - text: Articles

      - text: Presentations

      - text: Dashboards

      - text: Blog

      - text: How-To
        href: HowTo/index.qmd

      - text: About
        href: about.qmd

    tools:
      - icon: tools
        menu:
          - text: Fiddle Editor
            href: https://dotnetfiddle.net/  
            target: _blank

          - text: Rextester Editor
            href: https://rextester.com/l/csharp_online_compiler/
            target: _blank

          - text: Scholarhat Editor
            href: https://www.scholarhat.com/compiler/csharp/
            target: _blank            

          - text: Nextleap Editor
            href: https://nextleap.app/online-compiler/csharp-programming/
            target: _blank                        

  sidebar:
    - id: CSharp
      style: docked
      alignment: left
      border: false
      collapse-level: 1
      contents:
        - Courses/CSharp/index.qmd
        - Courses/CSharp/syllabus.qmd

        - section: "Chapters"
          contents: 
            - Courses/CSharp/ch01-language-basics.qmd
            - Courses/CSharp/ch02-decision-making.qmd
            - Courses/CSharp/ch03-iterations.qmd

        - section: "Exercises"    
          contents: 
            - Courses/CSharp/exercises.qmd

        - section: "Assignments"    
          contents: 
            - Courses/CSharp/assignments.qmd

        - section: "Appendices"
          contents: 
            - Courses/CSharp/Appendices/appendixA-binary-system.qmd
        
        - Courses/CSharp/references.qmd

  page-footer: 
    left: |
      <p>
        © {{< var copyright-years >}} Creative Ventures <br>
        Licensed under [Creative Commons]({{< var creativecommons-url >}}) CC BY 4.0
      </p>
    right: |
      <p>
        Built with [Quarto]({{< var quarto-url >}})
      </p>
    border: false

############################################################
# Format.
############################################################
format:
  html:
    theme:
      light: [Styles/theme.scss]
      dark: [Styles/theme.scss, Styles/theme-dark.scss]
    respect-user-color-scheme: true  

    date-format: medium

    anchor-sections: false ## Enables/disables an anchor link when hovering over a section title.
    smooth-scroll: true
    fig-cap-location: bottom
    tbl-cap-location: bottom  
    
    toc: true
    toc-title: ≣  
    toc-location: right
    toc-expand: true

    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 300px
      gutter-width: 1.5rem

    link-external-icon: true       ## Displays a special icon next to links that leave the current site.
    link-external-newwindow: true  ## Opens external links in a new browser window.

    # Global default appearance for all callouts.
    #
    # minimal - without header color and icon.
    # simple  - with icon only.
    # default - with header color and icon.
    #
    callout-appearance: simple

    code-copy: true ## Displays the code-copy button at all times.
       
    #embed-resources: true ## Produces a standalone HTML file with no external dependencies.

