############################################################
# Project.
############################################################
project:
  type: website
  resources:
    - Assets/resume.pdf

############################################################
# Language.
############################################################
language:
  search-text-placeholder: Search

############################################################
# Website.
############################################################
website:
  title: "Creative<br>Ventures"
  favicon: Assets/logo-icon.png
  page-navigation: true ## Provides next and previous page links in footer.
  back-to-top-navigation: true
  reader-mode: false ## Enables/disables the icon that hides sidebar and toc contents.
  bread-crumbs: false

  search:
    location: navbar
    type: textbox ## Selects the type of search UI.
    copy-button: true
    show-item-context: true ## Shows search result parents.
    collapse-after: 2

  navbar:
    logo: Assets/logo-icon.png
    pinned: true ## Keeps the navbar visible during page scrolling.
    toggle-position: left ## The position of the collapsed navbar toggle.
    tools-collapse: false ## Do not collapse tools when the display becomes narrow. Keep them on the navbar.

    left:
      - text: Home
        href: index.qmd
      
      - text: "Courses"
        menu:
          - text: C# Programming
            href: Courses/CSharp/index.qmd

          - text: ASP.NET Core Development
            href: Courses/ASPNET/index.qmd

          - text: Forex Trading
            href: Courses/Forex/index.qmd                         

      - text: Articles

      - text: Presentations

      - text: Dashboards

      - text: Blog

      - text: How-To
        href: HowTo/index.qmd

      - text: About
        href: about.qmd

    tools:
      - icon: tools
        menu:
          - text: Fiddle Editor
            href: https://dotnetfiddle.net/  
            target: _blank

          - text: Rextester Editor
            href: https://rextester.com/l/csharp_online_compiler/
            target: _blank

          - text: Scholarhat Editor
            href: https://www.scholarhat.com/compiler/csharp/
            target: _blank            

          - text: Nextleap Editor
            href: https://nextleap.app/online-compiler/csharp-programming/
            target: _blank                        

  sidebar:
    - id: CSharp
      style: docked
      alignment: left
      border: false
      collapse-level: 1
      pinned: true ## When collapsed, pin the sidebar to the top of the page.

      contents:
        - Courses/CSharp/index.qmd
        - Courses/CSharp/syllabus.qmd

        - section: Beginner
          contents:
            - Courses/CSharp/Ch01/notes01.qmd
            - Courses/CSharp/Ch02/notes02.qmd
            - Courses/CSharp/Ch03/notes03.qmd

        - section: Intermediate
          contents: 
            - Courses/CSharp/Ch11/notes11.qmd

        - section: Advanced
          contents: 
            - Courses/CSharp/Ch21/notes21.qmd

        - section: Appendices
          contents: 
            - Courses/CSharp/Appendices/appendixA-binary-system.qmd
            - Courses/CSharp/Appendices/appendixB-compilers.qmd
        
        - Courses/CSharp/references.qmd

  page-footer: 
    left: |
      <p>
        {{<fa brands creative-commons >}} {{< var copyright-years >}} Creative Ventures <br>
        Licensed under {{< fa brands creative-commons >}} [Creative Commons]({{< var creativecommons-url >}}) CC BY 4.0
      </p>
    right: |
      <p>
        Built with [Quarto]({{< var quarto-url >}}) <br>
        Powered by ? <br>
        Source code at {{< fa brands github >}} [GitHub]({{< var github-url >}})
      </p>
    border: false

############################################################
# Format.
############################################################
format:
  html:
    theme:
      light: [Styles/theme.scss]
      dark: [Styles/theme.scss, Styles/theme-dark.scss]

    anchor-sections: false ## Enables/disables an anchor link when hovering over a section title.
    code-copy: true ## Displays the code-copy button at all times.
    #embed-resources: true ## Produces a standalone HTML file with no external dependencies.
    link-external-icon: false ## Turns off a special icon next to links that leave the current site.
    link-external-newwindow: true ## Opens external links in a new browser window.
    smooth-scroll: true
    respect-user-color-scheme: true  
    tabsets: true
    title-block-categories: true
    toc: true
    toc-expand: true
    
    # Global default appearance for all callouts.
    #
    # minimal - without header color and icon.
    # simple  - with icon only.
    # default - with header color and icon.
    #
    callout-appearance: simple
    
    code-fold: show
    code-line-numbers: true
    code-overflow: scroll

    date-format: medium

    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 300px
      gutter-width: 1.5rem        

    fig-cap-location: bottom

    tbl-cap-location: bottom  
    
    toc-title: ≣ 
    toc-location: right
    



